Pdl datainnsmaling
navikt/medlemskap-oppslag pull request #234
Opened 2020-09-02 13:02 UTC by siljerisvik1

Nye felter fra PDL: 

Oppholdsadresse og Kontaktadresse

2020-09-02 13:04 UTC, siljerisvik1 commented on src/main/resources/pdl/hentPerson.graphql
> +      }
Ser her at jeg mulig har glemt noen felt vi trenger fra bostedsadresse

2020-09-02 13:09 UTC, siljerisvik1 commented on src/main/resources/pdl/hentPerson.graphql
> +      }
done

2020-09-03 08:20 UTC, haagenhasle reviewed
Ser generelt veldig fint ut, men jeg lurer på om det er mulig å forenkle koden litt mer, ref spørsmål inni koden.

2020-09-03 08:20 UTC, haagenhasle commented on src/main/kotlin/no/nav/medlemskap/domene/Personhistorikk.kt
> +data class Oppholdsadresse(
Trenger vi Oppholdsadresse og Kontaktadresse som egne klasser, eller kunne vi like gjerne brukt Adresse-klassen? Trenger vi noe annet enn å vite landkoden og gyldighetsperioden?

2020-09-03 13:00 UTC, haagenhasle requested changes
Kommentert på slack

2020-09-03 13:01 UTC, haagenhasle commented on src/main/kotlin/no/nav/medlemskap/domene/Personhistorikk.kt
> +data class Oppholdsadresse(
Denne er fikset.

2020-09-04 09:58 UTC, haagenhasle approved these changes

2020-09-04 11:04 UTC, merged