Person som ikke finnes returnerer fant ikke person
navikt/medlemskap-oppslag pull request #288
Opened 2020-10-06 10:07 UTC by siljerisvik1

Har gjort et forsøk på bedre feilmeldinger om person ikke finnes.

2020-10-08 11:00 UTC, olekvernberg requested changes
Ser bra ut. 
Savner en ServerTest som sjekker at responsen er en 404 dersom hovedbrukeren ikke finnes.

2020-10-09 12:45 UTC, olekvernberg approved these changes

2020-10-12 09:54 UTC, haagenhasle approved these changes
Enig med Ole Christian, kunne vært fint med en test eller to på at riktig respons blir gitt. Ellers ser dette fint ut altså! :)

2020-10-12 09:54 UTC, haagenhasle commented on src/main/kotlin/no/nav/medlemskap/routes/CreateDatagrunnlag.kt
> +    val dataOmBarn: MutableList<DataOmBarn> = ArrayList()
Jeg vil gi deg den samme utfordringen som jeg ga Ole Christian for en stund tilbake - se om du klarer å skrive kode med mer bruk av funksjonell/deklarativ stil, ikke så imperativt som det du har gjort her. Jeg vil f.eks tro at koden du har her kunne vært skrevet som dette:
```
fnrBarn
            .map{ hentPersonHistorikkForBarn(it, services, callId) }
            .filterNotNull()
            .map { dataOmBarn.add(DataOmBarn(it)) }
```
Og IntelliJ vil da tom anbefale deg å forkorte det ned til det følgende:
```
fnrBarn.mapNotNull { hentPersonHistorikkForBarn(it, services, callId) }
            .map { dataOmBarn.add(DataOmBarn(it)) }
```
Jeg synes den typen kode er bedre, men klart, ymmv.. :-)

2020-10-13 08:26 UTC, merged