Sjekk om bruker er doed
navikt/medlemskap-oppslag pull request #296
Opened 2020-10-13 09:48 UTC by siljerisvik1

Datainnhenting for PDL 'Folkeregisterpersonstatus' og feltet 'Doedsfall'

2020-10-14 10:00 UTC, navperbirg reviewed
Du burde ha Cucumber-tester som viser mapping ved dødsfall.

2020-10-14 10:16 UTC, olekvernberg requested changes
Det burde finnes en test som har en annen personstatus enn bosatt. Burde også finnes en cucumber-test som viser hva som skjer med ulike personstatus, gjerne hvor det finnes flere i en liste i doedsfall (og personstatuser) for det er ikke helt intuitivt hvorfor den er en liste med objekter.

2020-10-14 10:16 UTC, olekvernberg commented on pdl-client/src/main/resources/pdl/hentPerson.graphql
> +    			doedsdato
identering / curly braces

2020-10-14 10:16 UTC, olekvernberg commented on pdl-client/src/main/resources/pdl/hentPerson.graphql
> +    	 }
Ikke helt stødig på graphql, men mangler det et komma her? Er spørringen testet i altair?

2020-10-14 10:16 UTC, olekvernberg commented on src/main/kotlin/no/nav/medlemskap/domene/Personhistorikk.kt
> +    bosatt,
Verdier i enums skal være i upper case

2020-10-14 10:16 UTC, olekvernberg commented on src/main/kotlin/no/nav/medlemskap/services/pdl/mapper/PdlMapper.kt
> +    fun mapStatus(status: String): PersonStatus {
Denne typen mapping burde flyttes ut til enum-klassen ved å sette kodeverdien fra pdl i parentes bak enum. Eks. BOSATT("bosatt")

2020-10-14 10:19 UTC, siljerisvik1 commented on src/main/kotlin/no/nav/medlemskap/domene/Personhistorikk.kt
> +    bosatt,
Ja, men kommer slik fra PDL som string value, blir det da rett å lagre det som uppercase?

2020-10-14 10:19 UTC, siljerisvik1 commented on src/main/kotlin/no/nav/medlemskap/services/pdl/mapper/PdlMapper.kt
> +    fun mapStatus(status: String): PersonStatus {
Okei, fikser dette

2020-10-14 10:20 UTC, siljerisvik1 commented on pdl-client/src/main/resources/pdl/hentPerson.graphql
> +    			doedsdato
Det setter opp klassen i bygget, men jeg kan sjekke

2020-10-14 10:20 UTC, siljerisvik1 commented
> Det burde finnes en test som har en annen personstatus enn bosatt. Burde også finnes en cucumber-test som viser hva som skjer med ulike personstatus, gjerne hvor det finnes flere i en liste i doedsfall (og personstatuser) for det er ikke helt intuitivt hvorfor den er en liste med objekter.

2020-10-14 10:24 UTC, siljerisvik1 commented
> Det burde finnes en test som har en annen personstatus enn bosatt. Burde også finnes en cucumber-test som viser hva som skjer med ulike personstatus, gjerne hvor det finnes flere i en liste i doedsfall (og personstatuser) for det er ikke helt intuitivt hvorfor den er en liste med objekter.

Holder på med en cucumber-test for doedsfall nå, men foreløpig bruker vi ikke noen personstatuser. Eneste personstatus som er tenkt å brukes er "DOED" som en dobbelsjekk for doedsfall. Jeg vil ta en prat med Helle om andre statuser skal brukes, hvis ikke kan det jo hende at vi kun tar vare på doed statusen, men kan lage en cucumber-test på det iallefall.

2020-10-14 10:30 UTC, siljerisvik1 commented on pdl-client/src/main/resources/pdl/hentPerson.graphql
> +    	 }
Skal sjekke

2020-10-14 10:57 UTC, olekvernberg commented on src/main/kotlin/no/nav/medlemskap/domene/Personhistorikk.kt
> +    bosatt,
Ja, sett kodeverdien som kommer fra pdl i parentes

2020-10-15 20:13 UTC, siljerisvik1 commented on src/main/kotlin/no/nav/medlemskap/domene/Personhistorikk.kt
> +    bosatt,
Gjort

2020-10-15 20:13 UTC, siljerisvik1 commented on src/main/kotlin/no/nav/medlemskap/services/pdl/mapper/PdlMapper.kt
> +    fun mapStatus(status: String): PersonStatus {
Gjort

2020-10-20 08:12 UTC, closed without merging