bruker mer informasjon fra SAF til å filtrere data
navikt/medlemskap-oppslag pull request #580
Opened 2022-10-05 16:54 UTC by hjmNav

2022-10-06 05:56 UTC, StianSDouzette requested changes
Ser bra ut. Det er bare en liten ting som kanskje burde endres

2022-10-06 05:56 UTC, StianSDouzette commented on src/main/kotlin/no/nav/medlemskap/domene/Dokument.kt
> +                return date.isAfter(today.minusYears(1))
Er det riktig å bruke today og ikke første dag for søknaden? Hva om bruker søker om sykepenger 1 år etter at de har vært syk?

2022-10-07 11:31 UTC, StianSDouzette reviewed
Noen spørsmål

2022-10-07 11:31 UTC, StianSDouzette commented on src/main/kotlin/no/nav/medlemskap/domene/Dokument.kt
> +            try {
Hvilke potensielle feil skal denne håndtere?

2022-10-07 11:31 UTC, StianSDouzette commented on src/main/kotlin/no/nav/medlemskap/domene/Dokument.kt
> +                return return datoOpprettet.isAfter(firstDayOf2011)
dobbel return?

2022-10-07 11:33 UTC, hjmNav commented on src/main/kotlin/no/nav/medlemskap/domene/Dokument.kt
> +            try {
Teoretisk feil dersom dato streng som kommer fra SAF ikke klarer å bli parset til en LocalDateTime

2022-10-07 11:33 UTC, hjmNav commented on src/main/kotlin/no/nav/medlemskap/domene/Dokument.kt
> +                return return datoOpprettet.isAfter(firstDayOf2011)
ja, en return i IF og en return i Else.. som sagt.. kunne vert skrevet mye bedre.. kom gjerne med forslag..

2022-10-07 11:35 UTC, hjmNav commented on src/main/kotlin/no/nav/medlemskap/domene/Dokument.kt
> +            val relevantDatoJournalFort = this.relevanteDatoer?.find { it.datotype == Datotype.DATO_JOURNALFOERT }
den vil finne den første med datotype DATO_JOURNALFORT.. skal teoretisk sett ikke være flere av denne typen..
vi er ikke interessert i andre relevante datoer

2022-10-07 11:39 UTC, StianSDouzette commented on src/main/kotlin/no/nav/medlemskap/domene/Dokument.kt
> +                return return datoOpprettet.isAfter(firstDayOf2011)
Viser egentlig til `**return return** datoOpprettet.isAfter(firstDayOf2011)` 🙂

2022-10-10 13:16 UTC, merged